### ISSUE TITLE
Absenzen werden nicht mehr einberechnet

### ISSUE THREAD

**Issue by kalanorek** [simonroth/hakuna-team-life-balancer#1]
Ich bin ein grosser Fan deines Tools. Leider funktioniert es seit einigen Tagen nicht mehr richtig. 

Es wird zwar geladen und summiert die Anzahl Personen, welche angezeigt werden richtig. Es beachtet aber die Absenzen nicht mehr. Egal ob Absenzen (bewilligte oder angefragte) vorhanden sind oder nicht zeigt er immer die Total anwesenden Personen an. Es wirkt, alls hätten sich die "Feldbezeichungen" der Absenzen verändert. Machst du für das Tool noch Wartung/Weiterentwicklung oder soll ich lieber mit den internen Entwicklern schauen? Gruss, sth

![Absenzen_Mitarbeiter_·_hakuna](https://user-images.githubusercontent.com/16493002/232785983-6dc69a9b-56b0-4247-b1cb-a6be8eb729e1.png)

**Comment by bohemianoid** [comment]
Hallo sth, vielen Dank für deine Anfrage. Es freut mich, dass dich das Tool unterstützt.

Leider habe ich aktuell keinen Zugriff auf hakuna, um das Tool zu warten. Tut mir leid…
